name: lavivion-test-job

volumes:
  db:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 1381:1381
      - 1382:1382
    volumes:
      - ./:/web-app:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /web-app
    depends_on:
      - php

  php:
    # image: php:8.1-fpm-alpine
    build:
      dockerfile: ./php.dockerfile
    # container_name: site-php
    volumes:
      - ./:/web-app
    working_dir: /web-app
    user: 1000:1000

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lavivion
      POSTGRES_DB: lavivion
      POSTGRES_PASSWORD: lavivion

