name: lavivion-test-job

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./:/web-app:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /web-app
    depends_on:
      - php

  php:
    image: php:8.1-fpm-alpine
    # container_name: site-php
    volumes:
      - ./:/web-app
    working_dir: /web-app
    user: 1000:1000

